
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/proj-organic-w24-6pm-2
owner: ucsb-cs156-w24
repo_name: proj-organic-w24-6pm-2
pull_requests: [{"author":{"id":"U_kgDOB2_BEg","is_bot":false,"login":"kjlee2504","name":"Kevin Lee"},"headRefName":"kevin-join","number":30,"title":"KL - FEATURE: [Frontend] Normal User Join Action","url":"https://github.com/ucsb-cs156-w24/proj-organic-w24-6pm-2/pull/30"}]
