
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/proj-organic-w24-6pm-2
owner: ucsb-cs156-w24
repo_name: proj-organic-w24-6pm-2
pull_requests: [{"author":{"id":"MDQ6VXNlcjQ1NTE5MDIy","is_bot":false,"login":"mbharti12","name":"Mihir B"},"headRefName":"mb-organic-courses-dates-bug-fix","number":35,"title":"fixed course dates bug ","url":"https://github.com/ucsb-cs156-w24/proj-organic-w24-6pm-2/pull/35"},{"author":{"id":"U_kgDOB2-wIw","is_bot":false,"login":"thienanvuu","name":"Thienan Vu"},"headRefName":"Thienan-InaccurateIcon","number":34,"title":"Thienan inaccurate icon","url":"https://github.com/ucsb-cs156-w24/proj-organic-w24-6pm-2/pull/34"},{"author":{"id":"MDQ6VXNlcjkxMjk1MDY3","is_bot":false,"login":"vincentlinzhu","name":"Vincent Zhu"},"headRefName":"Vincent-organic-lastOnlineBug","number":33,"title":"Vincent organic last online bug","url":"https://github.com/ucsb-cs156-w24/proj-organic-w24-6pm-2/pull/33"}]
